SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECOND = 0.3
PLAYER_ACCELERATION = 550
PLAYER_DRAG = 0.98

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5

PLAYER_LIVES = 3
INVULNERABILITY_TIME = 2.0

ASTEROID_SCORE_LARGE = 20
ASTEROID_SCORE_MEDIUM = 50
ASTEROID_SCORE_SMALL = 100
