PLAYER_RADIUS         = 20
PLAYER_TURN_SPEED     = 300
PLAYER_SHOOT_SPEED    = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_ACCELERATION   = 550
PLAYER_DRAG           = 0.98
PLAYER_LIVES          = 3
INVULNERABILITY_TIME  = 2.0

ASTEROID_MIN_RADIUS   = 20
ASTEROID_KINDS        = 3
ASTEROID_SPAWN_RATE   = 0.8
ASTEROID_MAX_RADIUS   = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED_MIN    = 40
ASTEROID_SPEED_MAX    = 100

SHOT_RADIUS           = 5
SHOT_LIFETIME         = 2.0   # seconds before shot auto-kills

ASTEROID_SCORE_LARGE  = 20
ASTEROID_SCORE_MEDIUM = 50
ASTEROID_SCORE_SMALL  = 100

# Mode multipliers / tweaks
HARDCORE_SPEED_MULT      = 1.6
HARDCORE_SPAWN_MULT      = 0.45   # faster spawn = lower rate value
HARDCORE_SCORE_MULT      = 2
SURVIVAL_RAMP_INTERVAL   = 30.0   # seconds between difficulty ramps
SURVIVAL_RAMP_SPAWN_MULT = 0.85   # multiply spawn rate each ramp
